
import React from "react";
import './globals.css'; // Ensure global styles are applied
import { Space_Grotesk } from 'next/font/google';

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-grotesk', // Define a CSS variable
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={spaceGrotesk.className}>
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body className= "pt-8">

 <Navbar /> 
          {children}
          <Footer />
         </body>
    </html>
  );
}
